# Generated by Django 4.2.8 on 2024-01-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conversation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
