# Generated by Django 4.2.8 on 2024-01-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversation_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
